### ISSUE TITLE
Dependency warning message

### ISSUE THREAD

**Issue by caumond** [SevereOverfl0w/vizns#6]
Hi,
First thanks for your work, 
I have a warning message regarding the dependencies.

<img width="1698" alt="image" src="https://github.com/SevereOverfl0w/vizns/assets/11491686/a636f1d2-73a2-4f6b-ac42-003f71fe866c">

I suggest to update the deps.edn.

**Comment by SevereOverfl0w** [comment]
Fixed by #7.  Thanks for your contribution!
